### ISSUE TITLE
Setting Item Types Throws NullReferenceException Objects

### ISSUE THREAD

**Issue by JeffFerguson** [JeffFerguson/gepsio#1]
Setting item types on certain items throws an exception. Consider the following code:

```
var xbrlDoc = new XbrlDocument();
xbrlDoc.Load("http://xbrlsite.com/US-GAAP/BasicExample/2010-09-30/abc-20101231.xml");
```

This code causes the following exception to be thrown when `Load()` is called:
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at JeffFerguson.Gepsio.Item.SetItemType(IQualifiedName ItemTypeValue)
   at JeffFerguson.Gepsio.Item..ctor(XbrlFragment ParentFragment, INode ItemNode)
   at JeffFerguson.Gepsio.Fact.Create(XbrlFragment ParentFragment, INode FactNode)
   at JeffFerguson.Gepsio.XbrlFragment.ReadFacts()
   at JeffFerguson.Gepsio.XbrlFragment..ctor(XbrlDocument ParentDocument, INamespaceManager namespaceManager, INode XbrlRootNode)
   at JeffFerguson.Gepsio.XbrlDocument.Parse(IDocument doc)
   at Load.Program.LoadFromUrl() in C:\Users\jefff\Source\Repos\gepsio\Examples\Load\Program.cs:line 22
   at Load.Program.Main(String[] args) in C:\Users\jefff\Source\Repos\gepsio\Examples\Load\Program.cs:line 10
```

**Comment by JeffFerguson** [comment]
This issue is stemming from Gepsio's attempt to load facts whose namespace references externally defined schemas not explicitly loaded by the XBRL instance. In the example above, Gepsio is trying to hydrate an `Item` object from the following XBRL markup:

```
<dei:EntityRegistrantName contextRef="D-2010-Domain">ABC Company</dei:EntityRegistrantName>
```

The namespace for this item is defined as follows:

```
<xbrl
    ...
    xmlns:dei="http://xbrl.us/dei/2009-01-31" 
    ...
>
```

This namespace is defined by the SEC Document and Entity Information taxonomy, which is located physically at http://taxonomies.xbrl.us/us-gaap/2009/non-gaap/dei-2009-01-31.xsd. Since the document instance does not explicitly reference this schema (and it shouldn't), Gepsio has no loaded schema element information for the namespace. Since there is no loaded schema element information for the item, Gepsio cannot find the schema defining the element for the item, and the setting of the item type fails.

**Comment by JeffFerguson** [comment]
Fixed. A blog post further describing the issue is available at https://gepsio.wordpress.com/2017/10/05/next-release-to-support-automatic-loading-of-industry-standard-schemas/.
