### ISSUE TITLE
Nested Schema causing validation error

### ISSUE THREAD

**Issue by sreedesai** [JeffFerguson/gepsio#37]
Hi Jeff,

Getting an error when validating. It is probably not loading the nested schema files.

Fact NameOfOfficerWithCustodyOfCorporateBooks references a namespace with a URI of http://ferc.gov/form/2020-01-01/ferc, but no schema can be found for that namespace.
Schema element information is not available for this fact. 

Schema it is trying to import is in the same folder as the Main schema referencing it.

![image](https://user-images.githubusercontent.com/16884607/78275100-07b6f980-74c6-11ea-9478-d2046967292d.png)

**Comment by JeffFerguson** [comment]
Thanks for the report! Can you attach the XBRL instance file as well as any schemas or linkbase documents that you have locally? I'd like to be able to reproduce and debug the issue.

**Comment by sreedesai** [comment]
Here they are.

[fer-20200228-121430.zip](https://github.com/JeffFerguson/gepsio/files/4422373/fer-20200228-121430.zip)

[Form1.zip](https://github.com/JeffFerguson/gepsio/files/4422371/Form1.zip)

**Comment by JeffFerguson** [comment]
Thank you!

**Comment by JeffFerguson** [comment]
So the `fer-20200228-121430` ZIP is the main XBRL instance? Do you have everything in the same folder along with the contents of the other ZIP?

**Comment by sreedesai** [comment]
Form1.zip is the industry standard taxonomy and fer-20200228-121430.zip is the xbrl sample instance we are trying to validate against it.

**Comment by JeffFerguson** [comment]
Understood. Thank you. And do you happen to know which version of Gepsio you're using?

**Comment by sreedesai** [comment]
I am sorry, misread your question.  Yes, they are in the same folder. 
Library: 'Gepsio' version '2.1.0.16'

**Comment by JeffFerguson** [comment]
Thank you! I'll start looking at this today.

**Comment by JeffFerguson** [comment]
Yikes! Gepsio reports 1,827 validation errors on the document you provided. I'm guessing that the number will come down after the fix is applied. Thanks again for the samples. They helped me write a unit test for this issue. I'm debugging the unit test and Gepsio interactions now.

**Comment by JeffFerguson** [comment]
Yep. Looks like a bug to me. Here is the schema reference chain that I see:

- The schema element for fact `NameOfOfficerWithCustodyOfCorporateBooks` is defined in `ferc-core_2020-01-01.xsd`
- `fer-20200228-121430.xml` is the XBRL instance document
- `fer-20200228-121430.xml` has a `<schemaRef>` to `ferc-all_2020-01-01.xsd`
- `ferc-all_2020-01-01.xsd` has an `<import>` of `ferc-core_2020-01-01.xsd`

I'll debug Gepsio's schema loading processes now.

**Comment by JeffFerguson** [comment]
As I suspected: Gepsio is not properly handling `<import>` directives in top-level schemas. I'll get to work on a fix.

**Comment by JeffFerguson** [comment]
Now this is interesting ... it seems as though some of the types are declared multiple times. Going to have to do some thinking about this scenario.

```
System.Xml.Schema.XmlSchemaException
  HResult=0x80131941
  Message=The global element 'http://ferc.gov/form/2020-01-01/ferc:AbandonmentOfLeases' has already been declared.
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e, XmlSeverityType severity)
   at System.Xml.Schema.BaseProcessor.AddToTable(XmlSchemaObjectTable table, XmlQualifiedName qname, XmlSchemaObject item)
   at System.Xml.Schema.Compiler.Prepare(XmlSchema schema, Boolean cleanup)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at JeffFerguson.Gepsio.Xml.Implementation.SystemXmlLinq.SchemaSet.Compile() in C:\Src\gepsio\JeffFerguson.Gepsio\Xml\Implementations\SystemXmlLinq\SchemaSet.cs:line 90
   at JeffFerguson.Gepsio.XbrlSchema.ReadAndCompile(String schemaPath, ISchema schema, ISchemaSet schemaSet) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlSchema.cs:line 246
   at JeffFerguson.Gepsio.XbrlSchema.LookForImports() in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlSchema.cs:line 637
   at JeffFerguson.Gepsio.XbrlSchema..ctor(XbrlFragment ContainingXbrlFragment, String SchemaFilename, String BaseDirectory) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlSchema.cs:line 195
   at JeffFerguson.Gepsio.XbrlFragment.ReadTaxonomySchemaReference(INode SchemaRefNode) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlFragment.cs:line 424
   at JeffFerguson.Gepsio.XbrlFragment.ReadTaxonomySchemaReferences() in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlFragment.cs:line 387
   at JeffFerguson.Gepsio.XbrlFragment..ctor(XbrlDocument ParentDocument, INamespaceManager namespaceManager, INode XbrlRootNode) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlFragment.cs:line 164
   at JeffFerguson.Gepsio.XbrlDocument.Parse(IDocument doc) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlDocument.cs:line 386
   at JeffFerguson.Gepsio.XbrlDocument.Load(String Filename) in C:\Src\gepsio\JeffFerguson.Gepsio\XbrlDocument.cs:line 181
   at JeffFerguson.Gepsio.Test.IssueTests._37.Issue37Test.VerifyFixForIssue37() in C:\Src\gepsio\JeffFerguson.Gepsio.Test\IssueTests\37\Issue37Test.cs:line 40
```

**Comment by sreedesai** [comment]
Thank you for your quick turnaround. The fix will be a big help.

**Comment by JeffFerguson** [comment]
You're quite welcome ... although, as I mentioned, the imports are causing some elements, such as `http://ferc.gov/form/2020-01-01/ferc:AbandonmentOfLeases`, to be defined more than once, and, as a result, the schema set doesn't compile. Not yet sure how to handle that yet.

**Comment by JeffFerguson** [comment]
Hang on .. that might be my error, not the schema's. More in a bit.

**Comment by sreedesai** [comment]
Morning Jeff,

Any luck with this?

Thanks,
Sree

**Comment by JeffFerguson** [comment]
Hi! Still working on it today. Debugging some schema namespace issues. The `<import>` elements have some schema namespace information that Gepsio needs to keep track of.

**Comment by sreedesai** [comment]
Ok thank you Jeff

**Comment by JeffFerguson** [comment]
Progress! It takes a lot longer to load all of those schemas, but the validation errors have gone down from 1,827 to a mere 172 after the `<import>` processing. Now, I need to check to make sure I can find that fact that you were hoping to find.

**Comment by JeffFerguson** [comment]
It's good to see that the validation error count has gone way down, but I still need to put a little work in to find the fact. I'll keep on this one.

**Comment by sreedesai** [comment]
Awesome, thank you so much

**Comment by sreedesai** [comment]
Hi Jeff, checking if you have any update on this. Thank you.
